<?php

/**
 * Implements hook_init().
 */
function safe_styler_init() {

  $file_uri = path_to_theme() . "/css/safe-styles.css";
  if (file_exists($file_uri)) {
    drupal_add_css($file_uri, array(
      'type' => 'file',
      'group' => CSS_THEME,
      'every_page' => TRUE,
      'weight'=> 2000,
      'media' => 'all',
      'preprocess' => TRUE)
    );
  }
}

/**
 * Implements hook_form_system_theme_settings_alter()
 */
function safe_styler_form_system_theme_settings_alter(&$form, &$form_state) {

  // If safe-styles.css exists for the current theme create a form interface
  // for it, otherwise do nothing
  $file_uri = path_to_theme() . "/css/safe-styles.css";
  if (file_exists($file_uri)) {
    $css = file_get_contents($file_uri);
    drupal_set_message($css);      
    drupal_set_message(dpm($css));      

    // Add spectrum color picker js and css http://bgrins.github.io/spectrum
    // Requires libraries API and spectrum installed in
    // libraries/bgrins-spectrum as per color_field install instructions
    drupal_add_js(libraries_get_path('bgrins-spectrum') . '/spectrum.js');
    drupal_add_css(libraries_get_path('bgrins-spectrum') . '/spectrum.css');
    $spectrum_js = 'jQuery(".spectrum").spectrum({
      showInput: true,
      allowEmpty: true,
      showAlpha: true,
      showInitial: true,
      showInput: true,
      preferredFormat: "rgb",
      clickoutFiresChange: true,
      showButtons: false
    });';
    drupal_add_js($spectrum_js, array(
      'type' => 'inline',
      'scope' => 'footer',
      'weight' => 5)
    );


    $layout_header  = '<div class=""><div class="layout-header theme-settings-header clearfix">';
    $layout_header .= '<h1>' . t('Safe Styler Settings') . '</h1>';
    //$layout_header .= '<p class="docs-link"><a href="http://adaptivethemes.com/documentation/adaptivetheme-7x-3x" title="View online documentation" target="_blank">View online documentation</a></p>';
    //$layout_header .= '<p class="logo-link"><a href="http://adaptivethemes.com" title="Adaptivethemes.com - Rocking the hardest since 2006" target="_blank"><img class="at-logo" src="' . $logo . '" /></a></p>';
    $layout_header .= '</div>';

    $form['safe_styler'] = array(
      '#type' => 'vertical_tabs',
      '#description' => t('Layout'),
      '#prefix' => $layout_header,
      '#suffix' => '</div>',
      '#weight' => -10,
      //'#attached' => array(
      //  'css' => array(drupal_get_path('theme', 'adaptivetheme') . '/css/at.settings.form.css'),
      //),
    );

    // Parse CSS file into array
    $rules = _safe_styler_css2array($css);

    // Covert CSS rules array to form elements
    foreach($rules AS $rule) {

      // Get and use CSS rule comment as title of vertical tab
      $title = $rule['comment'];
      $form['safe_styler'][$title] = array(
        '#type' => 'fieldset',
        '#title' => $title,
      );

      // Get and store CSS selector in hidden form field
      $selector = $rule['selector'];
      $form['safe_styler'][$title]['css_selector'] = array(
        '#type' => 'hidden',
        '#value' => $selector,
      );

      // Process CSS declarations
      $declarations = $rule['declarations'];
      foreach($declarations AS $property=>$value) {
        $form['safe_styler'][$title][$property] = array(
          '#type' => 'textfield',
          '#title' => _safe_styler_property2label($property),
          '#default_value' => $value,
          '#attributes' => array('class' => array('spectrum')), 
        );
      }
    }
    
    // Attach custom submit handler to the form
    $form['#submit'][] = '_safe_styler_system_theme_settings_submit';
  }
}


function _safe_styler_system_theme_settings_submit(&$form, &$form_state) {

  $css = $form_state['values']['safe_styler_css'];

  // Save CSS file to theme
  $file_uri = path_to_theme() . "/css/safe-styles.css";
  file_unmanaged_save_data($css, $file_uri, FILE_EXISTS_REPLACE);
}

/**
 *  Convert CSS (including above-rule comments) into an array.
 */
function _safe_styler_css2array($css)
{
  $results = array();

  // Find CSS comments and rules using regex voodoo
  $regex_comment = '/\*(.*?)\*/';
  $regex_selector = '(.*?)';
  $regex_declarations = '\{(.*?)\}';
  $regex_pattern = '#' . $regex_comment . $regex_selector . $regex_declarations . '#sm';
  preg_match_all($regex_pattern, $css, $matches);

  // Process each match 
  foreach($matches[0] AS $i=>$match)
  {
    $results[$i]['comment'] = trim($matches[1][$i]);
    $results[$i]['selector'] = trim($matches[2][$i]);
    $declarations = explode(';', $matches[3][$i]);
    foreach($declarations AS $declaration)
    {
      if (strlen(trim($declaration)) > 0) // for missing semicolon on last element, which is legal
      {
        list($property, $value) = explode(':', $declaration);
        $results[$i]['declarations'][trim($property)] = trim($value);
      }
    }
  }

  return $results;
}

/**
 *  Convert CSS property to form field label.
 */
function _safe_styler_property2label($property) {
  return ucwords(str_replace("-", " ", $property));
}

/**
 *  Convert form field label to CSS property.
 */
function _safe_styler_label2property($label) {
  return strtolower(str_replace(" ", "-", $label));
}